@url = http://192.168.0.180/api
//@url = http://localhost:3000/api


// API CLIENTES
//OBTENER TODOS LOS USUARIOS
GET {{url}}/usuarios
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4

//OBTENER USUARIO POR ID
###
GET {{url}}/usuarios/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4

//CREAR USUARIO
###
POST {{url}}/usuarios
Content-Type: application/json

{
"nombre": "Jairo Mauricio",
"apellido": "Haro Velasco",
"ci": "1003638978",
"usuario": "jharo",
"password": "1234567",
"fecha_nac": "1986-03-02",
"fecha_cont": "2015-01-07",
"genero": "M",
"rol": "A"
}



###
PUT {{url}}/usuarios/3
Content-Type: application/json

{

  "nombre": "Edison Paul",
  "apellido": "Haro Yepez",
  "ci": "1003638970",
  "usuario": "pharo",
  "password": "1234567",
  "fecha_nac": "1995-05-03",
  "fecha_cont": "2019-01-07",
  "genero": "M",
  "rol": "T"
}

###
DELETE {{url}}/usuarios/10



////////////////////////////////////////////////////////////////
//////////// LOGIN     ////////////////////////////////////////

//LOGIN 
###
POST {{url}}/login
Content-Type: application/json

{
"usuario": "jharo",
"password": "1234567"
}