//@url = http://192.168.0.180/api
@url = http://localhost:3000/api


// API CLIENTES
//OBTENER TODOS LOS USUARIOS
GET {{url}}/usuarios
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4

//OBTENER USUARIO POR ID
###
GET {{url}}/usuarios/54
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4

//CREAR USUARIO
###
POST {{url}}/usuarios
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4
Content-Type: application/json

{
"nombre": "Jairo Mauricio",
"apellido": "Haro Yepez",
"ci": "1003638978",
"usuario": "jharo",
"password": "1234567",
"fecha_nac": "1993-06-03",
"fecha_cont": "2015-01-07",
"genero": "M",
"rol":[
        {
            "rol": "Bodega",
            "funcion": 1
        },
        {
            "rol": "Bodega",
            "funcion": 2
        },
        {
            "rol": "Administrador",
            "funcion": 1
        }
    ]


}



###
PUT {{url}}/usuarios/54
Content-Type: application/json

{

  "nombre": "Jairo Paul",
  "apellido": "Haro Yepez",
  "ci": "1003638970",
  "usuario": "jharo",
  "password": "1234567",
  "fecha_nac": "1995-05-03",
  "fecha_cont": "2019-01-07",
  "genero": "M",
  "rol": "T"
}

###
DELETE {{url}}/usuarios/10



////////////////////////////////////////////////////////////////
//////////// LOGIN     ////////////////////////////////////////

//LOGIN 
###
POST {{url}}/login
Content-Type: application/json

{
"usuario": "eharo",
"password": "1234567"
}


//////////////////////////////////////////////////////////////
///////////////////// roles //////////////////////////////////
//OBTENER LOS ROLES
###
GET {{url}}/funciones


###
GET {{url}}/funciones/54




//////////////////////////////////////////////////////////////
///////////////////// Prueba //////////////////////////////////
//OBTENER LOS ROLES
###
GET {{url}}/prueba


###
GET {{url}}/funciones/54
