//@url = http://192.168.0.180/api
@url = http://localhost:3000/api


//-----------------------------------------------------------
//               AGENDA                                      |
//-----------------------------------------------------------


//OBTENER TODOS LA AGENDA
###
GET {{url}}/agenda/preagenda
Authorization: {{TOKEN_AUX}}

//OBTENER TODOS LA AGENDA DE UNA FECHA ESPECIFICA
###
GET {{url}}/agenda/2025-04-09
Authorization: {{TOKEN_AUX}}

//OBTENER TODOS LOS TRABAJOS AGEDADOS A UN TECNICO
###
GET {{url}}/agenda/mis-trabajos-tec/81
Authorization:{{TOKEN_AUX}}


//OBTENER LA SOLUCION DE UN TRABAJO AGENADDO
###
GET {{url}}/agenda/sol/151
Authorization:{{TOKEN_AUX}}



//OBTENER LOS TRABAJOS PENDIENTES DE LA FECHA
###
GET {{url}}/agenda/pendientes/2025-06-01
Authorization:{{TOKEN_AUX}}




//CREAR TRABAJO EN AGENDA
###
POST {{url}}/agenda/agenda-sop
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{
    "age_tipo": "LOS",
    "ord_ins": "109681",
    "age_id_tipo": "316",
    "age_diagnostico":"CLIENTE REPORTA LUZ ROJA EN LA ONT",
    "age_coordenadas":"-0.953052, -78.632262"
}


//ATUALIZA CON FECHA HORA VEHICULO Y TECNICO
###
PUT {{url}}/agenda/edita-hora/75
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{
  "age_vehiculo":"F17",
  "age_hora_inicio": "14:00",
  "age_hora_fin": "16:00",
  "age_fecha": "2025-03-28"
}

//ATUALIZA LA SOLUCION Y ESTADO
###
PUT {{url}}/agenda/edita-sol/75
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{
  "age_estado":"CONCLUIDO",
 "age_solucion":"Se arregla "
}


