//@url = http://192.168.0.160/api
@url = http://localhost:3000/api


//-----------------------------------------------------------
//               CAJAS                                     |
//-----------------------------------------------------------


//OBTIENE UNA CAJAS POR ID
//router.get("/:id_vis", checkToken, getVisById);
###
GET {{url}}/cajas/41
Authorization: {{TOKEN_AUX}}


//CREAR CAJAS
//router.post("/", checkToken, createVis);
###
POST {{url}}/cajas
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{

     "caja_hilo" : "1",
    "caja_nombre" : "PON_LAT_OFOP_1",
    "caja_tipo" : "PON"
}

//ACTUALIZAR CAJAS
//router.put("/:id_vis", checkToken, updateVisById);
###
PUT {{url}}/cajas/46
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{
  "caja_coordenadas": "RESUELTO",
  "caja_observacion":"EL ARREGLO"
}
