//@url = http://192.168.0.180/api
@url = http://localhost:3000/api


//-----------------------------------------------------------
//               IMAGENES                                      |
//-----------------------------------------------------------


//OBTENER LAS IMAGENES DE LA INSTALACION SEGUN NOMBRE TABLA Y UN ID
###
GET {{url}}/imagenes/download/neg_t_instalaciones/103521
Authorization: {{TOKEN_AUX}}


//OBTENER LAS IMAGENES DE LA VISITA SEGUN NOMBRE TABLA Y UN ID
###
GET {{url}}/imagenes/download/neg_t_vis/41
Authorization: {{TOKEN_AUX}}


//OBTENER UN ARRAY CON LAS INFORMACION TODAS LAS VISITAS POR NOMBRE DE TABLA Y UNA ORD_INS
//router.get("/downloadvisitas/:tabla/:ord_ins",getArrayAllInfoVisitasByTableAndId);
###
GET {{url}}/imagenes/downloadvisitas/neg_t_vis/103521
Authorization: {{TOKEN_AUX}}
