//@url = http://192.168.0.160/api
@url = http://localhost:3000/api


//-----------------------------------------------------------
//               INSTALACIONES                              |
//-----------------------------------------------------------

//OBTENER INSTALACION POR ID
###
GET {{url}}/instalaciones/18
Authorization: {{TOKEN_AUX}}


//CREAR INSTALACION
###
POST {{url}}/instalaciones
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{
  "ord_ins": 103801,
  "nombre": "Butters",
  "apellido": "Stotch",
  "cedula": "0501234567",
  "tipo": "FIBRA",
  "plan": "400 MBPS",
  "telefonos": "55555555555",
  "coordenadas": "-0.8544, -0.5544",
  "direccion": "Calle Falsa 123"
}
