//@url = http://192.168.0.160/api
@url = http://localhost:3000/api


//-----------------------------------------------------------
//               OLT                                        |
//-----------------------------------------------------------


//PRUEBA LA CONEXION A LA OLT
###
GET {{url}}/olt/test?debug=true&showCreds=true
Authorization: {{TOKEN_AUX}}



//PRUEBA LA CONEXION A LA OLT
###
GET {{url}}/olt/test?debug=true&showCreds=true&passEol=CR
Authorization: {{TOKEN_AUX}}


//PRUEBA LA CONEXION A LA OLT
###
GET {{url}}/olt/test?debug=true&showCreds=true&userEol=CR&passEol=CR
Authorization: {{TOKEN_AUX}}





//PRUEBA LA CONEXION A LA OLT
###
GET {{url}}/olt/test?debug=true&showCreds=true&typeMsUser=20&typeMsPass=30&passEol=CR
Authorization: {{TOKEN_AUX}}


