//@url = http://192.168.0.160/api
@url = http://localhost:3000/api


//-----------------------------------------------------------
//               SOPORTES                                   |
//-----------------------------------------------------------



//OBTENER TODOS LOS SOPORTES DE LA BASE DE DATOS
###
GET {{url}}/soportes
Authorization: {{TOKEN_AUX}}
//OBTENER SOPORTES PENDIENTES POR REVISAR
###
GET {{url}}/soportes/pendientes
Authorization: {{TOKEN_AUX}}

//OBTENER SOPORTES PENDIENTES POR CONCLUIR
###
GET {{url}}/soportes/concluir
Authorization: {{TOKEN_AUX}}



//OBTENER SOPORTE POR ORDINS
###
GET {{url}}/soportes/349
Authorization: {{TOKEN_AUX}}


//CREAR SOPORTE
###
POST {{url}}/soportes
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{

    "ord_ins": 103801,
    "reg_sop_opc": 2,
    "reg_sop_tel": "55555555555",
    "reg_sop_registrado_por_id": "54",
    "reg_sop_coment_cliente": "Sin servicio desde las 10am",
  //  "reg_sop_nombre": "Butters",
     "reg_sop_coordenadas": "-0.8544, -0.5544"

}

//ACEPTAR EL SOPORTE POR NOC
###
PUT {{url}}/soportes/286
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{ 
    "reg_sop_noc_id_acepta":54
}


//OBTENER MIS SOPORTES DE NOC
###
GET {{url}}/soportes/revisados
Authorization: {{TOKEN_AUX}}


//OBTENER MIS SOPORTES DE NOC
###
GET {{url}}/soportes/diario/2025-10-11
Authorization: {{TOKEN_AUX}}



//OBTENER MIS SOPORTES DE TECNICO
###
GET {{url}}/soportes/mis-soportes-tec/81
Authorization: {{TOKEN_AUX}}

//ACTUALIZAR ESTADO UN SOPORTE
###
PUT {{url}}/soportes/mis-soportes/solucion/287
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{ 
    "reg_sop_estado":"RESUELTO",
     "reg_sop_sol_det":"se esta revisando"
}


//OBTENER LOS SOPORTES VISITA Y LOS
###
GET {{url}}/soportes/listar-tecnico
Authorization: {{TOKEN_AUX}}

//ACTUALIZAR TECNICO PARA  UN SOPORTE
###
PUT {{url}}/soportes/asignar-tecnico/119531
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{ 
    "reg_sop_tec_asignado":78
}

