//@url = http://192.168.0.160/api
@url = http://localhost:3000/api


//-----------------------------------------------------------
//               TURNOS                                      |
//-----------------------------------------------------------


### Listar turnos sin filtros
GET {{url}}/turnos
Authorization: {{TOKEN_AUX}}

### Listar turnos filtrados
GET {{url}}/turnos?sucursal=COTOPAXI&fecha_desde=2025-12-01&fecha_hasta=2025-12-31
Authorization: {{TOKEN_AUX}}