//@url = http://192.168.0.160/api
@url = http://localhost:3000/api


//OBTENER TODOS LOS USUARIOS
###
GET {{url}}/usuarios
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4


//OBTENER USUARIO POR ID
###
GET {{url}}/usuarios/54
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4


//OBTENER TODOS LOS USUARIOS AGENDA-TECNICOS
###
GET {{url}}/usuarios/agenda-tecnicos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4


//CREAR USUARIO
###
POST {{url}}/usuarios
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4
Content-Type: application/json

{
"nombre": "DARWIN JESUS",
"apellido": "MONTENEGRO LAGOS",
"ci": "0401111075",
"usuario": "DARW",
"password": "1234567",
"fecha_nac": "1993-06-03",
"fecha_cont": "2015-01-07",
"genero": "M",
"rol":[3,13,14]
}


//EDITAR USUARIO POR ID
###
PUT {{url}}/usuarios/92
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4
Content-Type: application/json

{
"nombre": "NORMA ODILA",
"apellido": "DELGADO NARVAEZ",
"ci": "0401274352",
"usuario": "ndelgado",
"password": "1234567",
"fecha_nac": "1993-06-03",
"fecha_cont": "2015-01-07",
"genero": "F",
"rol":[3,10,14]
}

//ELIMINAR UN USUARIO POR ID
###
DELETE {{url}}/usuarios/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4


////////////////////////////////////////////////////////////////
//////////// LOGIN ////////////////////////////////////////

//LOGIN 
###
POST {{url}}/login
Content-Type: application/json

{
"usuario": "eharo",
"password": "1234567"
}


//////////////////////////////////////////////////////////////
///////////////////// FUNCIONES DEL PERSONAL //////////////////////////////////
//OBTENER TODAS LAS FUNCIONES DE LA BASE DE DATOS
###
GET {{url}}/funciones
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4


//OBTIENE LAS FUNCIONES ASIGANADAS POR ID
###
GET {{url}}/funciones/54
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJBIiwiaWF0IjoxNzM0OTk3OTM5fQ.nsTjYmIITRS3ihmUshYMyVGt743lSEuV42IN9CGajz4



