//@url = http://192.168.0.160/api
@url = http://localhost:3000/api



//-----------------------------------------------------------
//                   LOGIN                                   |
//-----------------------------------------------------------

//LOGIN 
###
POST {{url}}/login
Content-Type: application/json

{
"usuario": "jharo",
"password": "1234567"
}


//LOGIN 
###
GET {{url}}/login/me
Authorization: {{TOKEN_AUX}}

//LOGOUT
###
POST {{url}}/login/not
Content-Type: application/json

{
"usuario_id": 54
}



//-----------------------------------------------------------
//                   USUARIOS                               |
//-----------------------------------------------------------



//OBTENER TODOS LOS USUARIOS
###
GET {{url}}/usuarios
Authorization: {{TOKEN_AUX}}

//OBTENER USUARIO POR ID
###
GET {{url}}/usuarios/54
Authorization: {{TOKEN_AUX}}

//OBTENER TODOS LOS USUARIOS AGENDA-TECNICOS
###
GET {{url}}/usuarios/agenda-tecnicos
Authorization: {{TOKEN_AUX}}

//CREAR USUARIO
###
POST {{url}}/usuarios
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{
"nombre": "DARWIN JESUS",
"apellido": "MONTENEGRO LAGOS",
"ci": "0401111075",
"usuario": "DARW",
"password": "1234567",
"fecha_nac": "1993-06-03",
"fecha_cont": "2015-01-07",
"genero": "M",
"rol":[3,13,14]
}


//EDITAR USUARIO POR ID
###
PUT {{url}}/usuarios/92
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{
"nombre": "NORMA ODILA",
"apellido": "DELGADO NARVAEZ",
"ci": "0401274352",
"usuario": "ndelgado",
"password": "1234567",
"fecha_nac": "1993-06-03",
"fecha_cont": "2015-01-07",
"genero": "F",
"rol":[3,10,14]
}

//ELIMINAR UN USUARIO POR ID
###
DELETE {{url}}/usuarios/10
Authorization: {{TOKEN_AUX}}




//-----------------------------------------------------------
//                FUNCIONES DEL PERSONAL                    |
//-----------------------------------------------------------


//OBTENER TODAS LAS FUNCIONES DE LA BASE DE DATOS
###
GET {{url}}/funciones
Authorization: {{TOKEN_AUX}}

//OBTIENE LAS FUNCIONES ASIGANADAS POR ID
###
GET {{url}}/funciones/54
Authorization: {{TOKEN_AUX}}


