//@url = http://192.168.0.160/api
@url = http://localhost:3000/api


//-----------------------------------------------------------
//               VISITA                                     |
//-----------------------------------------------------------


//OBTIENE UNA VISITA POR ID
//router.get("/:id_vis", checkToken, getVisById);
###
GET {{url}}/vis/41
Authorization: {{TOKEN_AUX}}


//CREAR VISITA
//router.post("/", checkToken, createVis);
###
POST {{url}}/vis
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{
    "ord_ins": 103802,
    "vis_estado" : "PENDIENTE",
    "vis_diagnostico": "CAMBIAR EL ROUTER Y ONT",
    "vis_coment_cliente":"EL INTERNET VIENE Y VA",
    "vis_tipo":"VISITA"
}

//ACTUALIZAR VISITA
//router.put("/:id_vis", checkToken, updateVisById);
###
PUT {{url}}/vis/46
Authorization: {{TOKEN_AUX}}
Content-Type: application/json

{
  "vis_estado": "RESUELTO",
  "vis_solucion":"EL ARREGLO"
}
